-- Atualiza Status das mensagens
DECLARE
  CURSOR c_messages IS
    SELECT MESSAGE_ID,JOB_MESSAGE FROM
    LB2REFRESH_MESSAGES JOIN LB2REFRESH_JOBS USING (JOB_ID)
    WHERE 1=1
      AND JOB_ID = 1
      and READ = 0 FOR UPDATE OF READ;
BEGIN
  FOR r IN c_messages
  LOOP
    dbms_output.put_line('Mensagem:'||r.job_message);
    UPDATE LB2REFRESH_MESSAGES SET READ = 1 WHERE CURRENT OF c_messages;
  END LOOP;
END;

/*
  FLUXO DO JOB TRACKER
*/

-- 1 - INICIANDO O LB2REFRESH
INSERT INTO LB2REFRESH (REFRESH_ID,START_TIME) VALUES (1,SYSTIMESTAMP);
COMMIT;

DELETE FROM LB2REFRESH WHERE REFRESH_ID = 1;

-- 1 - INICIANDO UM PRIMEIRO JOB. EXEMPLO: REFRESH_CLEAN
INSERT INTO LB2REFRESH_JOBS (JOB_ID,START_TIME,JOB_STATUS,REFRESH_ID)
VALUES (1,SYSTIMESTAMP,1,1);
COMMIT;

-- JOB INSERINDO DADOS
INSERT INTO LB2REFRESH_MESSAGES (MESSAGE_ID,JOB_MESSAGE,JOB_ID,READED)
VALUES (1,'Removendo conexões do usuário',1,0);
INSERT INTO LB2REFRESH_MESSAGES (MESSAGE_ID,JOB_MESSAGE,JOB_ID,READED)
VALUES (2,'Verificando se as conexões foram removidas para o usuário TASY',1,0);
INSERT INTO LB2REFRESH_MESSAGES (MESSAGE_ID,JOB_MESSAGE,JOB_ID,READED)
VALUES (3,'Todas as conexões com o usuário TASY foram mortas!',1,0);
commit;