/*
  BUILD SCHEMA

 */
/*
  Drops

  drop table LB2REFRESH_MESSAGES;
  drop table LB2REFRESH_JOBS;
  drop table LB2REFRESH;

 */
CREATE TABLE LB2REFRESH(
  REFRESH_ID NUMBER,
  START_TIME DATE,
  END_TIME DATE);

ALTER TABLE LB2REFRESH ADD CONSTRAINT PK_LB2REFRESH PRIMARY KEY (REFRESH_ID);

DROP TABLE LB2REFRESH_JOBS;

CREATE TABLE LB2REFRESH_JOBS(
  JOB_ID NUMBER,
  START_TIME DATE,
  END_TIME DATE,
  JOB_MESSAGE VARCHAR2(4000),
  JOB_STATUS NUMBER,
  REFRESH_ID NUMBER
);

ALTER TABLE LB2REFRESH_JOBS ADD CONSTRAINT PK_LB2REFRESH_JOBS PRIMARY KEY (JOB_ID);

ALTER TABLE LB2REFRESH_JOBS ADD CONSTRAINT FK_LB2REFRESH_JOBS FOREIGN KEY (REFRESH_ID)
REFERENCES LB2REFRESH (REFRESH_ID);

CREATE TABLE LB2REFRESH_MESSAGES(
  MESSAGE_ID NUMBER,
  JOB_MESSAGE VARCHAR2(4000),
  JOB_ID NUMBER,
  READ NUMBER
);

ALTER TABLE LB2REFRESH_MESSAGES ADD CONSTRAINT PK_LB2REFRESH_MESSAGES
PRIMARY KEY (MESSAGE_ID);

ALTER TABLE LB2REFRESH_MESSAGES ADD CONSTRAINT FK_LB2REFRESH_MESSAGES_JOBS
FOREIGN KEY (JOB_ID) REFERENCES LB2REFRESH_JOBS (JOB_ID);


/*
  READ = 0 -- NÃO LIDA
  READ = 1 -- LIDA
*/

/*
    TRACK JOB MODULE

START JOB
-----------
1 - Método insere um novo JOB com seu IMPORT_ID
2 - Método seta JOB_STATUS=1

GRAVAR MENSAGEM
---------------
1 - Thread faz um insert na LB2REFRESH_MESSAGES passando o JOB_ID
---------------

REGISTRAR MENSAGEM NO LOG
------------------------
1 - Thread faz um select na LB2REFRESH_MESSAGES passando o JOB_ID
2 - Thread faz um update na mensagem alterando a flag READED para 1.


*/
